# print("usama maher")
# print("hello world")
# print("ahmad raza go to america for 2026 say inshallah")
# print("fizanali and brother is ahmad raza ")
# print("hammara pass asi motor ho jis ko ham apana matakab control kar sakha")
# print("inshallaha assa time agha ga jab ham iot devies ko apana matakab control kar sakha gha ")
# print ("function sab apply karana ahaw gha ")
# print     ("45+890\676*67")
("x")(56+78)
print("x")